'\" t
.\"     Title: xwinfo
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 02/02/2014
.\"    Manual: Xwinfo Manual
.\"    Source: Xwinfo 0.1
.\"  Language: English
.\"
.TH "XWINFO" "1" "02/02/2014" "Xwinfo 0\&.1" "Xwinfo Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xwinfo \- Print window informations
.SH "SYNOPSIS"
.sp
\fBxwinfo\fR \fIOPTIONS\fR [\fIWID\fR \&...]
.SH "DESCRIPTION"
.sp
xwinfo prints the informations requested by the given options regarding the window IDs given as argument\&.
.SH "OPTIONS"
.PP
\fB\-h\fR
.RS 4
Print the synopsis to standard output and exit\&.
.RE
.PP
\fB\-v\fR
.RS 4
Print the version information to standard output and exit\&.
.RE
.PP
\fB\-c\fR
.RS 4
Print the class name\&.
.RE
.PP
\fB\-i\fR
.RS 4
Print the instance name\&.
.RE
.PP
\fB\-n\fR
.RS 4
Print the window title\&.
.RE
.PP
\fB\-t\fR
.RS 4
Print the window type\&.
.RE
.PP
\fB\-s\fR
.RS 4
Print the window state\&.
.RE
.PP
\fB\-g\fR
.RS 4
Print the geometry (as
\fIwidth height x y\fR)\&.
.RE
.SH "AUTHOR"
.sp
Bastien Dejean <nihilhill at gmail\&.com>
